### ISSUE TITLE
CircleCI - 2.0 Release Requirements

### ISSUE THREAD

**Issue by KyleTryon** [indeni/cloudrail-circleci-orb#18]
Hello all,
I have reviewed the orb in its current form and provided a list of suggested changes and requirements for CircleCI orb Partnership. When the changes are complete we should be merging as version 2.0.0 (currently 1.7.0).

## Requirements:
 - Address all open pull requests.
 - Update changelog for 2.0.0 release
 - Ensure all Usage Examples are up-to-date and showcasing the correct version for the release.

### Remove:
 - All "deprecated" components
   - The descriptions of these orb components suggest they are deprecated and suggest using an alternative instead. As this is a major version change (2.0.0) these should be removed.
   - https://github.com/indeni/cloudrail-circleci-orb/blob/main/src/commands/scan_terraform_junit.yml
   - https://github.com/indeni/cloudrail-circleci-orb/blob/main/src/jobs/scan_terraform_junit.yml
 
 ### Change:
  - API key should _not_ be of type `string`, instead use `env_var_name`
    - Users should not be entering their API keys in configs. Instead, they should provide the name of an environment variable. In the script, place a `$` before the env var name provided to access normally.
    - https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

 ### Considerations:
Some thoughts to discuss:

  - An Executor, and Command may not be necessary for this orb and could potentially be removed.
    - The Command as designed requires the CLI to be installed prior to use and the orb does not offer a way to install this, so it is dependent on the executor, meaning the user can not use this command in their own jobs with custom executors
    - The Executor on its own may not be useful for users, _unless_ they are attempting to make a custom version of the `scan_terraform` job.
    - It may be worth considering removing both the command and executor and instead, baking these directly into the `scan_terraform` job.
    - One way to ensure this job is able to handle more situations that might cause the user to want to create a new job of their own, is to add a parameter for custom steps after the checkout step. This way the user can simply utilize the job and if they need to run anything after checkout but prior to the scan, they can.
    - https://circleci.com/docs/2.0/reusing-config/#steps

Great work and testing 👍

**Comment by yi2020** [comment]
@alexjurkiewicz heads up, the above is feedback from CircleCI's partner team. We'll incorporate your PRs, as well as @KyleTryon 's proposed changes, all into a 2.0 release.

@KyleTryon - regarding your last thoughts to discuss, this has been brought up by @alexjurkiewicz and others. @ivantikal is currently working on a way to distribute the Cloudrail tool as a self-packaged command which can be used with existing executors, as well as our own. Still, we highly recommend using our own executor, as it's been heavily tested and will not be impacted by various quirks with users' own containers.

**Comment by KyleTryon** [comment]
> Still, we highly recommend using our own executor, as it's been heavily tested and will not be impacted by various quirks with users' own containers.

For this reason, I would suggest limiting the orb components to just a `job`, that way the user will not be confused or attempt to use the command outside of your executor.

**Comment by yi2020** [comment]
So no command? In that case, how do you structure the tests in the config of this project?

**Comment by KyleTryon** [comment]
> So no command? In that case, how do you structure the tests in the config of this project?

Unless we think there is a scenario where a user would have a use-case where defining their own job (using the command) would be preferred. Otherwise, this will be easier for users and more simple in the documentation.

For testing, it is much the same. Currently, you are testing the command within the context of a job (integration-test-1). That allows you to test the command. To test a job, you can just skip the job creation and test it directly.

You can see an example of this here: https://github.com/CircleCI-Public/aws-elastic-beanstalk-orb/blob/9b1f4d45264087c392814ae7f7b3736caf3badc4/.circleci/config.yml#L107

```
 integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-1:
          context: [orb-aws-eb-testing]
          matrix:
              parameters:
                compute: [python, base]
...
      - aws-elastic-beanstalk/deploy:
 ...
```

`integration-test-1` is just one of three jobs being tested, one of the other three jobs is [aws-elastic-beanstalk/deploy](https://github.com/CircleCI-Public/aws-elastic-beanstalk-orb/blob/9b1f4d45264087c392814ae7f7b3736caf3badc4/.circleci/config.yml#L116) which is coming directly from the orb and utilized exactly the same way a user would access the job.

There is one mistake in this example though I am going to correct right now. The deployment job `orb-tools/dev-promote-prod-from-commit-subject` should require _all three_ of these jobs to pass: https://github.com/CircleCI-Public/aws-elastic-beanstalk-orb/blob/9b1f4d45264087c392814ae7f7b3736caf3badc4/.circleci/config.yml#L140

**Comment by yi2020** [comment]
I actually do know users would want to use the command - once we support it outside our own executor. So is it best to remove it now, and re-add it later (once we support running Cloudrail on containers that aren't our own)?

**Comment by KyleTryon** [comment]
I think that would be best 👍
